# Generated by Django 5.1.1 on 2025-02-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_product_rename_menu_item_menu_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='guest_count',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
