# Generated by Django 5.1.1 on 2025-03-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_booking_guest_count_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meu',
        ),
    ]
